afronevents/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from sitemap import *
handler404 = 'publicpages.views.custom404'

urlpatterns = [
    url(r'^manage/', admin.site.urls),
    url(r'^', include('publicpages.urls', namespace="pages")),
    #url(r'^page/',include('publicpages.urls', namespace="pages")),
    url(r'^photos/',include('gallery.urls', namespace="gallery")),
    url('^events/', include('events.urls', namespace='events')),
    url(r'^daguerre/', include('daguerre.urls')),


]

sitemaps = {
    'events': EventSitemap,
    'contact':AfroneventsSitemap(['contact']),
    'public': PublicPageSitemap
}






if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.conf.urls import url
from events.views import  EventListView, EventDetailView
urlpatterns = [
    url(r'(?P<slug>[\w-]+|)/$', EventDetailView.as_view(),name= "event"),
    url(r'^$', EventListView.as_view(), name = "events"),
    ]

gallery/urls.py
from django.conf.urls import url
from gallery.views import GalleryList


urlpatterns = [
    url(r'(?P<service>[\w-]+|)/$', GalleryList.as_view(), name="filterByService"),
    url(r'^$', GalleryList.as_view(),name= "gallery")
               ]

gallery/models.py
from django.db import models

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit,Adjust
from afronevents.settings import ENV_PATH, BASE_DIR

from datetime import datetime

from events.models import Event
from services.models import Service


class Gallery(models.Model):






    photos = models.ImageField(upload_to='service_photo_thumbs', null=True, blank=True)
    thumbnail = ImageSpecField([Adjust(sharpness=1.1),
                                ResizeToFit(257, 247)], source='photos',
                               format='JPEG', options={'quality': 100})

    title = models.CharField(max_length=255, blank=True, null=True)
    service = models.ForeignKey(Service, null=True, blank=True)
    event = models.ForeignKey(Event, null=True, blank=True)
    description = models.TextField(blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title
    #code

gallery/views.py
from django.shortcuts import render
from django.views.generic import ListView

from services.models import Service
from .models import Gallery


class GalleryList(ListView):
    model = Gallery

    template_name = "gallery/gallery.html"
    paginate_by = 28

    def get_queryset(self):
        queryset = super(GalleryList, self).get_queryset()
        service = self.kwargs.get("service")

        if service is not None:
            queryset = queryset.filter(service__slug=service).order_by('-created')

        return queryset

    def get_context_data(self, **kwargs):
        ctx = super(GalleryList,self).get_context_data(**kwargs)
        ctx["services"] = Service.objects.all()
        return ctx

templates/gallery/gallery.html
 {% extends 'header.html' %}
{% load staticfiles %}
{% load daguerre %}



{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'assets/' %}spaced.css">
<link rel="stylesheet" type="text/css" href="{% static '' %}assets/lightbox.min.css">
 
<section class="event-grid-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="event-gallery-filter">
                        <li data-filter="all" class="filter active">
                            <span><a href="{% url 'gallery:gallery' %}">All</a></span>
                        </li>
                        {% for s in services %}
                        <li data-filter=".{{ s.slug }}" class="filter">
                            <span><a href="{% url 'gallery:filterByService' s.slug %}"> {{ s.title }}</a></span>
                        </li>
                        {%  endfor %}

                    </ul>
                </div>

            </div>
          </div>


    <!--start nicdark_container-->
    <div class="">
                         

     <div class="row event-gallery-content" data-filter-class="filter">

    
    {% for p in gallery_list %}
    <a href="{{   p.photos.url  }}" data-lightbox="gallery" class="{{ p.service.slug }}">
        <img src="{{  p.photos.url }}" class="imgspaced">
    </a>
    
    {% empty %}

{% endfor %}
     </div>
     <div class="row">
                <div class="col-md-12">
                {% if is_paginated %}
                    <div class="paginations text-center">
                        <ul>

                         {% if page_obj.has_previous %}
                        <li><a href="/photos/?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left" area-hidden="true"></i> </a></li>
                        {% endif %}


                        {% if is_paginated %}





                    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li > <a  class="active">{{ i }}</a></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}

    {% endfor %}
                            {% endif %}
                            {% if page_obj.has_next %}
                            <li><a href="/photos/?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                            {% endif %}

                        </ul>
                    </div>
                    {% endif %}

                <br/> <div class="showing-page pull-right">
                        <p><span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span></p>
                    </div>

                </div>
            </div>
    </div>
    <!--end nicdark_container-->
            
</section>
<!--end section-->







{% endblock %}