afronevents/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from sitemap import *
handler404 = 'publicpages.views.custom404'

urlpatterns = [
    url(r'^manage/', admin.site.urls),
    url(r'^', include('publicpages.urls', namespace="pages")),
    #url(r'^page/',include('publicpages.urls', namespace="pages")),
    url(r'^photos/',include('gallery.urls', namespace="gallery")),
    url('^events/', include('events.urls', namespace='events')),
    url(r'^daguerre/', include('daguerre.urls')),


]

sitemaps = {
    'events': EventSitemap,
    'contact':AfroneventsSitemap(['contact']),
    'public': PublicPageSitemap
}






if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.conf.urls import url
from events.views import  EventListView, EventDetailView
urlpatterns = [
    url(r'(?P<slug>[\w-]+|)/$', EventDetailView.as_view(),name= "event"),
    url(r'^$', EventListView.as_view(), name = "events"),
    ]

gallery/urls.py
from django.conf.urls import url
from gallery.views import GalleryList


urlpatterns = [
    url(r'(?P<service>[\w-]+|)/$', GalleryList.as_view(), name="filterByService"),
    url(r'^$', GalleryList.as_view(),name= "gallery")
               ]

publicpages/urls.py
from django.conf.urls import url
from . import views

from .views import ContactUs, StaticPage, AboutUs, home, Services


urlpatterns = [
    url(r'^$', home, name='home'),
    #url(r'^$', current_datetime, name="new-home"),
    url(r'^(?P<slug>\w+|)$', StaticPage, name = "page"),
    url(r'^contact/$', ContactUs.as_view(), name= "contact"),
    url(r'^about/$', AboutUs, name="about"),
    url(r'^services/$', Services, name="services"),
    ]

templates/header.html
{% load staticfiles %}
{% load daguerre %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Afron Concept International, Nigeria </title>

	<!-- responsive meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- master stylesheet -->
	 	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">


	<!-- responsive stylesheet -->
	<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery.bxslider.css' %}">

 <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="js/respond.js"></script>
	<![endif]-->


</head>



<body>

<!--Start Top area-->
<section class="top-area">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="social-linls pull-left">
                    <a href=""><i class="fa fa-facebook myfb" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>


                    <a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="top-right pull-right">
                    <ul class="login-register clearfix">
                        <li><a href="tel:+2348177401893">Have any questions? Call: +234 817 7401 893</a></li>
                        <li><a href="">info@afronevents.com</a></li>

                    </ul>


                </div>
            </div>

        </div>
    </div>
</section>
<!--End Top area-->

<!--Start header area-->
<header class="header">
    <div class="container">
        <div class="clearfix">
            <div class="logo pull-left">
                <a href="{% url 'pages:home' %}">
                    <img src="{% static '/' %}img/resources/logo.png" alt="Afron Concept International">
                </a>
            </div>
            <div class="header-right pull-right clearfix">
                {% comment %}
                <div class="header-searchbar pull-right">
                    <div class="nav-toggler-box ">
                        <button type="button" data-toggle="collapse" data-target="#mainNavWrapper" aria-expanded="true" aria-controls="mainNavWrapper">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <form class="search-form" action="#">
                        <input type="text" placeholder="search">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>

{% endcomment %}
                <div class="nav-footer collapse pull-right" id="mainNavWrapper">
                    <ul>
                        <li><a href="{% url 'pages:home' %}">HOME</a></li>
                         <li><a href="/services/">Services</a></li>
                        <li><a href="{% url 'events:events' %}">EVENTS</a></li>
                        <li><a href="{% url 'gallery:gallery' %}">GALLERY</a></li>

                        <li><a href="{% url 'pages:contact' %}">CONTACT</a></li>

                        <li><a href="{% url 'pages:about' %}">ABOUT US</a></li>





                    </ul>
                </div>

            </div>
        </div>
    </div>
</header>
<!--End header area-->

{% block content %}
{% endblock %}


<!--Start footer area-->
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <!--Start single footer widget-->
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="single-footer-widget">
                    <h5 class="title">About Us</h5>
                    <div class="about-text">
                        <p>AFRON CONCEPT INTERNATIONAL LTD is a highly professional global event company that specializes in business-to-business, regional and international conferences, workshops, master classes and training. We are also primary providers of interpretation, translation and conference services in Nigeria with our corporate head office in Abuja.


</p>
                    </div>
                </div>
            </div>
            <!--End single footer widget-->
            <!--Start single footer widget-->
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="single-footer-widget">
                    <h5 class="title">Quicklinks</h5>
                    <ul class="quicklinks floatleft">



                         <li><a href="{% url 'pages:home' %}">HOME</a></li>
                         <li><a href="/services/">OUR SERVICES</a></li>
                        <li><a href="{% url 'events:events' %}">EVENTS</a></li>
                        <li><a href="{% url 'gallery:gallery' %}">GALLERY</a></li>




                    </ul>
                    <ul class="quicklinks floatright">
                         <li><a href="{% url 'pages:about' %}">ABOUT US</a></li>
                         <li><a href="{% url 'pages:contact' %}">CONTACT</a></li>

                        <li><a href="/manage/"> STAFF LOGIN </a></li>

                    </ul>
                </div>
            </div>
            <!--End single footer widget-->


        </div>
    </div>
</footer>
<!--End footer area-->

<!--Start footer bottom area-->
<section class="footer-bottom-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright-text text-center">
                    <p>Copyright &copy {% now 'Y' %}  Afron Concept International | All Rights Reserved | Powered by: Le Proghrammeen Solutions</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End footer bottom area-->

	<!-- main jQuery -->
	<script src="{% static 'assets/js/jquery-1.12.4.min.js' %}"></script>


	<!-- bootstrap -->
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<!-- bx slider -->

	<script src="{% static 'assets/js/jquery.stellar.js' %}"></script>
    <!-- owl carousel -->
	<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
	<!-- validate -->
	<script src="{% static 'assets/js/validate.js' %}"></script>
	<!-- mixit up -->
	<script src="{% static 'assets/js/jquery.mixitup.min.js' %}"></script>
	<!-- fancy box -->
	<script src="{% static 'assets/js/fancyapps-fancyBox/source/jquery.fancybox.pack.js' %}"></script>
	<!-- easing -->
	<script src="{% static 'assets/js/jquery.easing.min.js' %}"></script>

	<!-- gmap helper -->
	<script src="http://maps.google.com/maps/api/js?key=AIzaSyBLMubTsrBtGrwuBmoqK0q70Ms_cKQPSvg"></script>

 <script src="{% static 'assets/js/gmap.js' %}"></script>


	<!-- video responsive script -->
    <script src="{% static 'assets/js/jquery.fitvids.js' %}"></script>


    <script type="text/javascript" src="{% static '' %}assets/lightbox.min.js"></script>



    <script src="{% static 'assets/js/jquery-ui-1.11.4/jquery-ui.js' %}"></script>


	<!-- revolution scripts -->
	<script src="{% static 'assets/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
	<script src="{% static 'assets/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>


<script src="{% static 'assets/js/jquery.bxslider.min.js' %}" type="text/javascript"></script>


	<!-- thm custom script -->
	<script src="{% static 'assets/js/custom.js' %}" type="text/javascript"></script>



</body>
</html>

templates/header2.html
{% load staticfiles %}
{% load daguerre %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Afronevents</title>

	<!-- responsive meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- master stylesheet -->
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	<!-- responsive stylesheet -->
	<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

</head>



<body>

<!--Start Top area-->
<section class="top-area">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="social-linls pull-left">
                    <a href=""><i class="fa fa-facebook myfb" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-share-alt" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="top-right pull-right">
                    <ul class="login-register clearfix">
                        <li><a href="">Have any questions? Call: +2348177401893</a></li>
                        <li><a href="">info@afronevents.com</a></li>

                    </ul>


                </div>
            </div>

        </div>
    </div>
</section>
<!--End Top area-->

<!--Start header area-->
<header class="header">
    <div class="container">
        <div class="clearfix">
            <div class="logo pull-left">
                <a href="{% url 'home' %}">
                    <img src="{%  static  'img/resources/logo.png' %}" alt="Afron Events International Ltd" title="Afron Events International Ltd">
                </a>
            </div>
            <div class="header-right pull-right clearfix">
                <div class="header-searchbar pull-right">
                    <div class="nav-toggler-box ">
                        <button type="button" data-toggle="collapse" data-target="#mainNavWrapper" aria-expanded="true" aria-controls="mainNavWrapper">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <form class="search-form" action="#">
                        <input type="text" placeholder="search">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>

                <div class="nav-footer collapse pull-right" id="mainNavWrapper">
                    <ul>
                        <li><a href="{% url 'new-home' %}">HOME</a></li>
                         <li><a href="#">Services</a></li>
                        <li><a href="{% url 'events:events' %}">EVENTS</a></li>
                        <li><a href="{% url 'gallery:gallery' %}">GALLERY</a></li>

                        <li><a href="{% url 'pages:contact' %}">CONTACT</a></li>

                        <li><a href="{% url 'pages:about' %}">ABOUT US</a></li>





                    </ul>
                </div>

            </div>
        </div>
    </div>
</header>
<!--End header area-->

{% block content %}


{% endblock %}


<!--Start footer area-->
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <!--Start single footer widget-->
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="single-footer-widget">
                    <h5 class="title">About Us</h5>
                    <div class="about-text">
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
                    </div>
                </div>
            </div>
            <!--End single footer widget-->
            <!--Start single footer widget-->
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="single-footer-widget">
                    <h5 class="title">Quicklinks</h5>
                    <ul class="quicklinks floatleft">
                        <li><a href="">About Us</a></li>
                        <li><a href="">Our Philosophy</a></li>

                        <li><a href="">Our Services</a></li>
                    </ul>
                    <ul class="quicklinks floatright">

                        <li><a href="">FAQ & Help Center</a></li>

                        <li><a href="{{ /manage }}"> Staff Login </a></li>
                        <li><a href="">Careers</a></li>
                    </ul>
                </div>
            </div>
            <!--End single footer widget-->
            <!--Start single footer widget-->
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="single-footer-widget twitter-feed-widget">
                    <h5 class="title">Twitter Feed</h5>
                    <ul class="twitter-feed">
                        <li class="clearfix">
                            <div class="icon-holder">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </div>
                            <div class="text">
                                <p>smartup consetetur sadipscing elitr, sed diam nonumy...</p>
                                <span># 2 hours ago</span>
                            </div>
                        </li>
                        <li class="clearfix">
                            <div class="icon-holder">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </div>
                            <div class="text">
                                <p>@smartup  ceirmod tempor invidunt ut labore et dolore magna aliquyam erat...</p>
                                <span># 4 hours ago</span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <!--End single footer widget-->
            <!--Start single footer widget-->
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="single-footer-widget subscirbe-newsletter-form-widget">
                    <h5 class="title">Subscirbe Newsletter</h5>
                    <form class="subscirbe-newsletter-form" action="#">
                        <input type="text" name="name" placeholder="enter your name">
                        <input type="text" name="email" placeholder="enter your email">
                        <button type="submit">subscirbe now<i class="fa fa-angle-right" aria-hidden="true"></i></button>
                    </form>
                </div>
            </div>
            <!--End single footer widget-->
        </div>
    </div>
</footer>
<!--End footer area-->

<!--Start footer bottom area-->
<section class="footer-bottom-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright-text text-center">
                    <p>Copyright &copy {% now 'Y' %}  Afronevents | All Rights Reserved | Powered by: Le Proghrammeen Solutions</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End footer bottom area-->

	<!-- main jQuery -->
	<script src="{% static 'assets/js/jquery-1.12.4.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<!-- bx slider -->
	<script src="{% static 'assets/js/jquery.bxslider.min.js' %}"></script>
	<!-- count to -->
	<script src="{% static 'assets/js/jquery.countTo.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
	<!-- validate -->
	<script src="{% static 'assets/js/validate.js' %}"></script>
	<!-- mixit up -->
	<script src="{% static 'assets/js/jquery.mixitup.min.js' %}"></script>
	<!-- fancy box -->
	<script src="{% static 'assets/js/fancyapps-fancyBox/source/jquery.fancybox.pack.js' %}"></script>
	<!-- easing -->
	<script src="{% static 'assets/js/jquery.easing.min.js' %}"></script>

	<!-- gmap helper -->
	<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
	<!-- video responsive script -->
    <script src="{% static 'assets/js/jquery.fitvids.js' %}"></script>


    <script src="{% static 'assets/js/jquery-ui-1.11.4/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>


	<!-- revolution scripts -->
	<script src="{% static 'assets/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
	<script src="{% static 'assets/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>




	<!-- thm custom script -->
	<script src="{% static 'assets/js/custom.js' %}"></script>


</body>
</html>

templates/rfq.html
  


<section class="newsletter-area">
    <div class="newsletter">
        {% comment %}
        <h1>request for qoute </h1>
        <form class="news-letter-form" action="{% url 'pages:page' 'contact' %}" method="post">
            {%  csrf_token %}
            <input class="your-name" type="text" name="name" placeholder="enter your name">
            <input class="your-email" type="text" name="email" placeholder="enter your email">
            <textarea name="message"></textarea>
            <button class="sign-up" type="submit">submit request</button>
        </form>

        {% endcomment %}
    </div>
</section>